---
version: "3.2"
services:
  app:
    environment:
      - ALLOWED_HOSTS='*'
      - DATABASE_URL=postgres://silverstrike:secretpass@database/silverstrikedb
      - SECRET_KEY=PLprXpLzxemgLD57GPQQ84SBZdLVKFYg
    build: .
    # image: simhnna/silverstrike
    links:
      - database:database
    ports:
      - 8000:8000
  database:
    environment:
      POSTGRES_DB: silverstrikedb
      POSTGRES_USER: silverstrike
      POSTGRES_PASSWORD: secretpass
    image: postgres:10.3
    volumes:
      - ./silverstrikedb:/var/lib/postgresql/data
